#!/bin/bash

# Readline library configuration options.
# http://ss64.com/bash/syntax-inputrc.html

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Vi mode
set editing-mode vi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Ctrl-l to clear scren
Control-l: clear-screen

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# If there are multiple matches for completion,
# make TAB cycle through them.

TAB: menu-complete

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Searching files via partial match.

# ↑
"\e[A":history-search-backward
# ↓
"\e[B":history-search-forward

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Disable beeping and window flashing.

set bell-style none

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Use case-insensitive TAB autocompletion.

set completion-ignore-case on

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Perform partial completion on the first Tab press, and
# only start cycling full results on the second Tab press.

set menu-complete-display-prefix on

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Display a list of the matching files

set show-all-if-ambiguous on

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Immediately add a trailing slash when autocompleting symlinks to directories
set mark-symlinked-directories on

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Be more intelligent when autocompleting by also looking at the text after
# the cursor. For example, when the current line is "cd ~/src/mozil", and
# the cursor is on the "z", pressing Tab will not autocomplete it to "cd
# ~/src/mozillail", but to "cd ~/src/mozilla". (This is supported by the
# Readline used by Bash 4.)
set skip-completed-text on

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Show extra file information when completing, like `ls -F` does
set visible-stats on
