#!/usr/bin/env zsh
# Set zsh directory
export ZDOTDIR=$HOME/.zsh

# Local and host-specific overrides
LOCAL_RC=$HOME/.zshenv.local
test -f $LOCAL_RC && source $LOCAL_RC

# Stop (eg.) `git push github` from triggering:
# zsh: correct 'github' to '.github' [yes, no, edit, abort]?
export CORRECT_IGNORE_FILE='.*'

export PAGER=less

if which nvim &> /dev/null; then
  export VISUAL=$(which nvim)
  export EDITOR=$VISUAL
elif which vim &> /dev/null; then
  export VISUAL=$(which vim)
  export EDITOR=$VISUAL
else
  export VISUAL=$(which vi)
  export EDITOR=$VISUAL
fi

# if which emacsclient &> /dev/null; then
#   export VISUAL=$(which emacsclient)
#   export EDITOR=$VISUAL
# fi

# filename (if known), line number if known, falling back to percent if known,
# falling back to byte offset, falling back to dash
export LESSPROMPT='?f%f .?ltLine %lt:?pt%pt\%:?btByte %bt:-...'

# i = case-insensitive searches, unless uppercase characters in search string
# F = exit immediately if output fits on one screen
# M = verbose prompt
# R = ANSI color support
# S = chop long lines (rather than wrap them onto next line)
# X = suppress alternate screen
export LESS=iFMRSX

# Color man pages.
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;38;5;208m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[04;38;5;111m'

# colour ls listings
export CLICOLOR=true
