#!/usr/bin/env zsh

# Command aliases
if [ "$(uname -s)" == "Darwin" ]; then
    alias ls="gls -h --color=auto --group-directories-first"
else
    alias ls="ls -h --color=auto --group-directories-first"
fi

alias ll="ls -l"
alias la="ls -lA"
alias grep="grep --color=auto"
alias diff="diff --color=auto"
alias ....="cd ../.."
alias cd..="cd .."

if command -v nvim &> /dev/null; then
    alias vim=nvim # Use `\vim` or `command vim` to get the real vim.
    alias vi=nvim
fi
