#!/bin/sh

#### Autostart ####
xsetroot -cursor_name left_ptr
sxhkd &
$HOME/.config/polybar/launch.sh

#### Monitors ####
if [ -z "$(bspc query -M --names | grep DP-0)" ]; then
	bspc monitor DP-2 -d 1 2 3 4 5 6 7 8 9 10
else
	bspc monitor DP-2 -d 1 2 3 4 5
	bspc monitor DP-0 -d 6 7 8 9 10
fi

#### BSPWM configuration ####
bspc config border_width         	2
bspc config window_gap           	5
bspc config top_padding             20
bspc config split_ratio          	0.5
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config focus_follows_pointer	true
bspc config remove_disabled_monitors	true
bspc config remove_unplugged_monitors	true

#### BSPWM coloring ####
blue="#BD93F9"
grey="#BFBFBF"
bspc config focused_border_color	$blue
bspc config active_border_color		$grey
bspc config normal_border_color		$grey
bspc config presel_feedback_color	$blue

#### BSPWM rules ####
bspc rule -a Emacs state=tiled
bspc rule -a discord desktop=^6
bspc rule -a Zathura state=tiled
bspc rule -a Pcmanfm state=floating
