#!/bin/sh
# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

nitrogen --restore            # Set wallpaper
xset -b r rate 150 66         # Set a blazingly fast keyboard repeat rate and silence PC bell
numlockx &                    # Activate numlock key
picom --config /dev/null &    # Compositing manager
unclutter &                   # Hide idle cursor
dunst &                       # Notification system
udiskie -f "" &               # Automounter

# Map the caps lock key to super...
setxkbmap -layout es -variant cat -option caps:super && killall xcape 2>/dev/null ; xcape -e 'Super_L=Escape'

# Map the menu button to right super as well.
xmodmap -e 'keycode 135 = Super_R'

# Run redshift
redshift -l 41.38879:2.15899 -t 6500:3000 &

# Make main monitor the primary output
xrandr --output DP-2 --primary --auto

exec xmonad
