#!/bin/bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias ls="ls -h"
alias ll="ls -l"
alias la="ls -Al"
alias df="df -h"
alias grep="grep --color=auto"
alias diff="diff --color=auto"
alias vi="nvim"
alias vim="nvim"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Load OS specific aliases.

. "aliases/$OS/bash_aliases"
