#!/bin/sh
# start some nice programs

nitrogen --restore                  # Set wallpaper
xset r rate 300 50                  # Increase repetition key rate
compton -b --config /dev/null &     # Compositing manager
unclutter &                         # Hide idle cursor
sxhkd &                             # Universal bindings
dunst &                             # Notification system

# Map the caps lock key to super...
setxkbmap -layout es -variant cat -option caps:super && killall xcape 2>/dev/null ; xcape -e 'Super_L=Escape'

# Map the menu button to right super as well.
xmodmap -e 'keycode 135 = Super_R'

# Run redshift
redshift -l 41.38879:2.15899 &

# Make main monitor the primary output
xrandr --output DP-2 --primary --auto
