#!/usr/bin/env zsh

# Set some environment variables
export XDG_CONFIG_HOME=$HOME/.config
export ZDOTDIR=$XDG_CONFIG_HOME/zsh

# Local and host-specific overrides
if [[ -f "$ZDOTDIR/.zshenv.local" ]]; then
    source $ZDOTDIR/.zshenv.local
fi

# Add $XDG_CONFIG_HOME/bin/ to path for personal scripts
if [[ -d "$XDG_CONFIG_HOME/bin" ]]; then
    export PATH="$XDG_CONFIG_HOME/bin:$PATH"
fi

# Add $HOME/.local/bin/ to path for local binaries
if [[ -d "$HOME/.local/bin" ]]; then
    export PATH="$HOME/.local/bin:$PATH"
fi

# Stop (eg.) `git push github` from triggering:
# zsh: correct 'github' to '.github' [yes, no, edit, abort]?
export CORRECT_IGNORE_FILE='.*'

if command -v nvim &> /dev/null; then
  export EDITOR=nvim
else
  export EDITOR=vim
fi
export MANPAGER=less

# i = case-insensitive searches, unless uppercase characters in search string
# F = exit immediately if output fits on one screen
# M = verbose prompt
# R = ANSI color support
# S = chop long lines (rather than wrap them onto next line)
# X = suppress alternate screen
export LESS=iFMRSX

# Less colors
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;38;5;208m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[04;38;5;111m'
