name: Test shell scripts

on: push

jobs:
  build:
    runs-on: [ubuntu-latest, macos-latest] 
    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies (macOS)
      if: ${{ os == macos-latest }}
      run: brew install shellcheck
      
    - name: Run test script
      run: ./tests/shellcheck.sh
