name: Test shell scripts

on: push

jobs:
  build:
    runs-on: [ubuntu-latest, macos-latest] 
    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run test script
      run: ./tests/shellcheck.sh
