name: Test shell scripts

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install shellcheck
      run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
              apt install shellcheck
          else
              brew install shellcheck
          fi
 
    - name: Run test script
      run: ./tests/shellcheck.sh
